"""Create member-two commerce data foundation tables.

Revision ID: 20260728_0003
Revises: 20260727_0002
Create Date: 2026-07-28
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260728_0003"
down_revision: str | Sequence[str] | None = "20260727_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_trends",
        sa.Column("site", sa.String(length=32), nullable=False),
        sa.Column("category_external_id", sa.String(length=100), nullable=False),
        sa.Column("category_name", sa.String(length=200), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("search_index", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("sales_index", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("competition_index", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("average_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("growth_rate", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "average_price >= 0", name=op.f("ck_category_trends_average_price_nonnegative")
        ),
        sa.CheckConstraint(
            "competition_index >= 0", name=op.f("ck_category_trends_competition_nonnegative")
        ),
        sa.CheckConstraint("sales_index >= 0", name=op.f("ck_category_trends_sales_nonnegative")),
        sa.CheckConstraint("search_index >= 0", name=op.f("ck_category_trends_search_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_trends")),
        sa.UniqueConstraint("external_id", name=op.f("uq_category_trends_external_id")),
        sa.UniqueConstraint(
            "site", "category_external_id", "date", name="uq_category_trends_site_category_date"
        ),
    )
    op.create_table(
        "shops",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shops")),
        sa.UniqueConstraint("external_id", name=op.f("uq_shops_external_id")),
    )
    op.create_table(
        "orders",
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.Column("source_shop_external_id", sa.String(length=100), nullable=False),
        sa.Column("buyer_external_id", sa.String(length=100), nullable=False),
        sa.Column("site", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("order_status", sa.String(length=32), nullable=False),
        sa.Column("payment_status", sa.String(length=32), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("shipping_fee", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("discount_amount >= 0", name=op.f("ck_orders_discount_nonnegative")),
        sa.CheckConstraint("shipping_fee >= 0", name=op.f("ck_orders_shipping_fee_nonnegative")),
        sa.CheckConstraint("subtotal >= 0", name=op.f("ck_orders_subtotal_nonnegative")),
        sa.CheckConstraint("total_amount >= 0", name=op.f("ck_orders_total_nonnegative")),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_orders_shop_id_shops"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("external_id", name=op.f("uq_orders_external_id")),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(
            "ix_orders_buyer_created", ["buyer_external_id", "source_created_at"], unique=False
        )
        batch_op.create_index(
            "ix_orders_shop_status_created",
            ["shop_id", "order_status", "source_created_at"],
            unique=False,
        )

    op.create_table(
        "products",
        sa.Column("shop_id", sa.Uuid(), nullable=False),
        sa.Column("source_shop_external_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("category_external_id", sa.String(length=100), nullable=False),
        sa.Column("category_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("site", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("sales_count", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("favorite_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("cost >= 0", name=op.f("ck_products_cost_nonnegative")),
        sa.CheckConstraint("price >= 0", name=op.f("ck_products_price_nonnegative")),
        sa.CheckConstraint("rating >= 0 AND rating <= 5", name=op.f("ck_products_rating_range")),
        sa.CheckConstraint(
            "shipping_cost >= 0", name=op.f("ck_products_shipping_cost_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_products_shop_id_shops"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("external_id", name=op.f("uq_products_external_id")),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(
            "ix_products_shop_status_updated", ["shop_id", "status", "updated_at"], unique=False
        )
        batch_op.create_index(
            "ix_products_site_category", ["site", "category_external_id"], unique=False
        )

    op.create_table(
        "customer_sessions",
        sa.Column("buyer_external_id", sa.String(length=100), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("intent", sa.String(length=50), nullable=False),
        sa.Column("risk_level", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_customer_sessions_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_customer_sessions_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_sessions")),
        sa.UniqueConstraint("external_id", name=op.f("uq_customer_sessions_external_id")),
    )
    with op.batch_alter_table("customer_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_customer_sessions_status_created", ["status", "source_created_at"], unique=False
        )

    op.create_table(
        "logistics_records",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("tracking_number", sa.String(length=100), nullable=False),
        sa.Column("carrier", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("origin", sa.String(length=200), nullable=False),
        sa.Column("destination", sa.String(length=200), nullable=False),
        sa.Column("estimated_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_location", sa.String(length=200), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_logistics_records_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_logistics_records")),
        sa.UniqueConstraint("external_id", name=op.f("uq_logistics_records_external_id")),
        sa.UniqueConstraint("order_id", name=op.f("uq_logistics_records_order_id")),
        sa.UniqueConstraint("tracking_number", name=op.f("uq_logistics_records_tracking_number")),
    )
    op.create_table(
        "skus",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("seller_sku", sa.String(length=100), nullable=False),
        sa.Column("variation_name", sa.String(length=100), nullable=False),
        sa.Column("variation_value", sa.String(length=200), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("weight", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("cost >= 0", name=op.f("ck_skus_cost_nonnegative")),
        sa.CheckConstraint("price >= 0", name=op.f("ck_skus_price_nonnegative")),
        sa.CheckConstraint("weight >= 0", name=op.f("ck_skus_weight_nonnegative")),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_skus_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skus")),
        sa.UniqueConstraint("external_id", name=op.f("uq_skus_external_id")),
        sa.UniqueConstraint("seller_sku", name=op.f("uq_skus_seller_sku")),
    )
    with op.batch_alter_table("skus", schema=None) as batch_op:
        batch_op.create_index("ix_skus_product_status", ["product_id", "status"], unique=False)

    op.create_table(
        "customer_messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("sender_type", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("message_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["customer_sessions.id"],
            name=op.f("fk_customer_messages_session_id_customer_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_messages")),
        sa.UniqueConstraint("external_id", name=op.f("uq_customer_messages_external_id")),
    )
    with op.batch_alter_table("customer_messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_customer_messages_session_time", ["session_id", "message_time"], unique=False
        )

    op.create_table(
        "inventory_records",
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_external_id", sa.String(length=100), nullable=False),
        sa.Column("warehouse_name", sa.String(length=200), nullable=False),
        sa.Column("available_stock", sa.Integer(), nullable=False),
        sa.Column("reserved_stock", sa.Integer(), nullable=False),
        sa.Column("safety_stock", sa.Integer(), nullable=False),
        sa.Column("stock_status", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "available_stock >= 0", name=op.f("ck_inventory_records_available_nonnegative")
        ),
        sa.CheckConstraint(
            "reserved_stock >= 0", name=op.f("ck_inventory_records_reserved_nonnegative")
        ),
        sa.CheckConstraint(
            "safety_stock >= 0", name=op.f("ck_inventory_records_safety_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
            name=op.f("fk_inventory_records_sku_id_skus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_records")),
        sa.UniqueConstraint("external_id", name=op.f("uq_inventory_records_external_id")),
        sa.UniqueConstraint("sku_id", "warehouse_external_id", name="uq_inventory_sku_warehouse"),
    )
    with op.batch_alter_table("inventory_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_inventory_status_updated", ["stock_status", "updated_at"], unique=False
        )

    op.create_table(
        "logistics_tracks",
        sa.Column("logistics_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["logistics_id"],
            ["logistics_records.id"],
            name=op.f("fk_logistics_tracks_logistics_id_logistics_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_logistics_tracks")),
        sa.UniqueConstraint("external_id", name=op.f("uq_logistics_tracks_external_id")),
    )
    with op.batch_alter_table("logistics_tracks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_logistics_tracks_record_event", ["logistics_id", "event_time"], unique=False
        )

    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.CheckConstraint("subtotal >= 0", name=op.f("ck_order_items_subtotal_nonnegative")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_order_items_unit_price_nonnegative")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["skus.id"], name=op.f("fk_order_items_sku_id_skus"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        sa.UniqueConstraint("external_id", name=op.f("uq_order_items_external_id")),
    )
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.create_index("ix_order_items_order", ["order_id"], unique=False)
        batch_op.create_index("ix_order_items_product", ["product_id"], unique=False)
        batch_op.create_index("ix_order_items_sku", ["sku_id"], unique=False)

    op.create_table(
        "reviews",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("buyer_external_id", sa.String(length=100), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_zh", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("sentiment_hint", sa.String(length=32), nullable=False),
        sa.Column("issue_type", sa.String(length=50), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name=op.f("ck_reviews_rating_range")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_reviews_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_reviews_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["skus.id"], name=op.f("fk_reviews_sku_id_skus"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("external_id", name=op.f("uq_reviews_external_id")),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reviews_product_created", ["product_id", "source_created_at"], unique=False
        )

    op.create_table(
        "returns_refunds",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("order_item_id", sa.Uuid(), nullable=False),
        sa.Column("buyer_external_id", sa.String(length=100), nullable=False),
        sa.Column("request_type", sa.String(length=32), nullable=False),
        sa.Column("reason_type", sa.String(length=50), nullable=False),
        sa.Column("reason_description", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_returns_refunds_amount_nonnegative")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_returns_refunds_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
            name=op.f("fk_returns_refunds_order_item_id_order_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_returns_refunds")),
        sa.UniqueConstraint("external_id", name=op.f("uq_returns_refunds_external_id")),
    )
    with op.batch_alter_table("returns_refunds", schema=None) as batch_op:
        batch_op.create_index(
            "ix_returns_refunds_order_status", ["order_id", "status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("returns_refunds", schema=None) as batch_op:
        batch_op.drop_index("ix_returns_refunds_order_status")

    op.drop_table("returns_refunds")
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index("ix_reviews_product_created")

    op.drop_table("reviews")
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_index("ix_order_items_sku")
        batch_op.drop_index("ix_order_items_product")
        batch_op.drop_index("ix_order_items_order")

    op.drop_table("order_items")
    with op.batch_alter_table("logistics_tracks", schema=None) as batch_op:
        batch_op.drop_index("ix_logistics_tracks_record_event")

    op.drop_table("logistics_tracks")
    with op.batch_alter_table("inventory_records", schema=None) as batch_op:
        batch_op.drop_index("ix_inventory_status_updated")

    op.drop_table("inventory_records")
    with op.batch_alter_table("customer_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_customer_messages_session_time")

    op.drop_table("customer_messages")
    with op.batch_alter_table("skus", schema=None) as batch_op:
        batch_op.drop_index("ix_skus_product_status")

    op.drop_table("skus")
    op.drop_table("logistics_records")
    with op.batch_alter_table("customer_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_customer_sessions_status_created")

    op.drop_table("customer_sessions")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index("ix_products_site_category")
        batch_op.drop_index("ix_products_shop_status_updated")

    op.drop_table("products")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index("ix_orders_shop_status_created")
        batch_op.drop_index("ix_orders_buyer_created")

    op.drop_table("orders")
    op.drop_table("shops")
    op.drop_table("category_trends")
    # ### end Alembic commands ###
