"""Create member-three analysis persistence tables.

Revision ID: 20260727_0002
Revises: 20260727_0001
Create Date: 2026-07-28
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.sqltypes import Text

revision: str = "20260727_0002"
down_revision: str | Sequence[str] | None = "20260727_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_templates",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_prompt_templates_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_templates")),
    )
    with op.batch_alter_table("prompt_templates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prompt_templates_key"), ["key"], unique=True)

    op.create_table(
        "product_contents",
        sa.Column("source_product_id", sa.String(length=100), nullable=False),
        sa.Column("site", sa.String(length=64), nullable=False),
        sa.Column("target_language", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_version", sa.String(length=100), nullable=True),
        sa.Column(
            "source_facts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("agent_task_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_task_id"],
            ["agent_tasks.id"],
            name=op.f("fk_product_contents_agent_task_id_agent_tasks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_product_contents_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_contents")),
        sa.UniqueConstraint(
            "source_product_id",
            "site",
            "target_language",
            name="uq_product_contents_product_site_language",
        ),
    )
    with op.batch_alter_table("product_contents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_product_contents_created_by_created_at", ["created_by", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_product_contents_product_language_status",
            ["source_product_id", "target_language", "status"],
            unique=False,
        )

    op.create_table(
        "product_selection_tasks",
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("agent_task_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "criteria",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_version", sa.String(length=100), nullable=True),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_task_id"],
            ["agent_tasks.id"],
            name=op.f("fk_product_selection_tasks_agent_task_id_agent_tasks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_product_selection_tasks_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_selection_tasks")),
    )
    with op.batch_alter_table("product_selection_tasks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_product_selection_tasks_created_by_created_at",
            ["created_by", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_product_selection_tasks_status_created_at", ["status", "created_at"], unique=False
        )

    op.create_table(
        "prompt_versions",
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "input_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "model_config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("version > 0", name=op.f("ck_prompt_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_prompt_versions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["prompt_templates.id"],
            name=op.f("fk_prompt_versions_template_id_prompt_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint("template_id", "checksum", name="uq_prompt_versions_template_checksum"),
        sa.UniqueConstraint("template_id", "version", name="uq_prompt_versions_template_version"),
    )
    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_prompt_versions_template_created_at", ["template_id", "created_at"], unique=False
        )

    op.create_table(
        "model_invocations",
        sa.Column("agent_task_id", sa.Uuid(), nullable=True),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "input_summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "output_summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "model_parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("timeout_ms", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("cost_currency", sa.String(length=8), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "completion_tokens >= 0",
            name=op.f("ck_model_invocations_completion_tokens_nonnegative"),
        ),
        sa.CheckConstraint(
            "duration_ms >= 0", name=op.f("ck_model_invocations_duration_ms_nonnegative")
        ),
        sa.CheckConstraint(
            "estimated_cost >= 0", name=op.f("ck_model_invocations_estimated_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "prompt_tokens >= 0", name=op.f("ck_model_invocations_prompt_tokens_nonnegative")
        ),
        sa.CheckConstraint(
            "retry_count >= 0", name=op.f("ck_model_invocations_retry_count_nonnegative")
        ),
        sa.CheckConstraint("timeout_ms > 0", name=op.f("ck_model_invocations_timeout_ms_positive")),
        sa.CheckConstraint(
            "total_tokens >= 0", name=op.f("ck_model_invocations_total_tokens_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["agent_task_id"],
            ["agent_tasks.id"],
            name=op.f("fk_model_invocations_agent_task_id_agent_tasks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_model_invocations_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_model_invocations_prompt_version_id_prompt_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_invocations")),
    )
    with op.batch_alter_table("model_invocations", schema=None) as batch_op:
        batch_op.create_index("ix_model_invocations_agent_task_id", ["agent_task_id"], unique=False)
        batch_op.create_index(
            "ix_model_invocations_model_created_at", ["model_name", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_model_invocations_status_created_at", ["status", "created_at"], unique=False
        )

    op.create_table(
        "product_selection_results",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("source_product_id", sa.String(length=100), nullable=False),
        sa.Column("site", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column(
            "metric_breakdown",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("recommendation_reason", sa.Text(), nullable=False),
        sa.Column(
            "risk_warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("data_completeness", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "data_sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "source_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "data_completeness >= 0 AND data_completeness <= 1",
            name=op.f("ck_product_selection_results_data_completeness_range"),
        ),
        sa.CheckConstraint("rank > 0", name=op.f("ck_product_selection_results_rank_positive")),
        sa.CheckConstraint(
            "total_score >= 0 AND total_score <= 100",
            name=op.f("ck_product_selection_results_total_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["product_selection_tasks.id"],
            name=op.f("fk_product_selection_results_task_id_product_selection_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_selection_results")),
        sa.UniqueConstraint("task_id", "rank", name="uq_product_selection_results_task_rank"),
        sa.UniqueConstraint(
            "task_id", "source_product_id", name="uq_product_selection_results_task_product"
        ),
    )
    with op.batch_alter_table("product_selection_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_product_selection_results_product_created_at",
            ["source_product_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_product_selection_results_task_rank", ["task_id", "rank"], unique=False
        )

    op.create_table(
        "generated_reports",
        sa.Column("report_type", sa.String(length=64), nullable=False),
        sa.Column("source_entity_type", sa.String(length=64), nullable=False),
        sa.Column("source_entity_id", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column(
            "data_sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "input_conditions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("model_invocation_id", sa.Uuid(), nullable=True),
        sa.Column("agent_task_id", sa.Uuid(), nullable=True),
        sa.Column("result_version", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_task_id"],
            ["agent_tasks.id"],
            name=op.f("fk_generated_reports_agent_task_id_agent_tasks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_generated_reports_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_invocation_id"],
            ["model_invocations.id"],
            name=op.f("fk_generated_reports_model_invocation_id_model_invocations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_reports")),
        sa.UniqueConstraint(
            "report_type",
            "source_entity_type",
            "source_entity_id",
            "result_version",
            name="uq_generated_reports_source_version",
        ),
    )
    with op.batch_alter_table("generated_reports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_generated_reports_source", ["source_entity_type", "source_entity_id"], unique=False
        )
        batch_op.create_index(
            "ix_generated_reports_status_created_at", ["status", "created_at"], unique=False
        )

    op.create_table(
        "product_content_versions",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "bullet_points",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("marketing_copy", sa.Text(), nullable=False),
        sa.Column(
            "source_facts_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "faq",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "sku_content",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "keywords",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "fact_check_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "compliance_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("change_type", sa.String(length=32), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("model_invocation_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_product_content_versions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["product_contents.id"],
            name=op.f("fk_product_content_versions_content_id_product_contents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_product_content_versions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_invocation_id"],
            ["model_invocations.id"],
            name=op.f("fk_product_content_versions_model_invocation_id_model_invocations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_product_content_versions_prompt_version_id_prompt_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_content_versions")),
        sa.UniqueConstraint(
            "content_id", "version", name="uq_product_content_versions_content_version"
        ),
    )
    with op.batch_alter_table("product_content_versions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_product_content_versions_content_created_at",
            ["content_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "review_analysis_results",
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("agent_task_id", sa.Uuid(), nullable=True),
        sa.Column("source_product_id", sa.String(length=100), nullable=False),
        sa.Column("site", sa.String(length=64), nullable=False),
        sa.Column(
            "requested_languages",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "input_conditions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("analyzer_version", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_version", sa.String(length=100), nullable=True),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("model_invocation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_task_id"],
            ["agent_tasks.id"],
            name=op.f("fk_review_analysis_results_agent_task_id_agent_tasks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_review_analysis_results_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_invocation_id"],
            ["model_invocations.id"],
            name=op.f("fk_review_analysis_results_model_invocation_id_model_invocations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_review_analysis_results_prompt_version_id_prompt_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_analysis_results")),
    )
    with op.batch_alter_table("review_analysis_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_review_analysis_results_product_created_at",
            ["source_product_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_review_analysis_results_status_created_at", ["status", "created_at"], unique=False
        )

    op.create_table(
        "product_improvement_reports",
        sa.Column("review_analysis_result_id", sa.Uuid(), nullable=False),
        sa.Column("source_product_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column(
            "data_sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "input_conditions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("model_invocation_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_product_improvement_reports_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_product_improvement_reports_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["model_invocation_id"],
            ["model_invocations.id"],
            name=op.f("fk_product_improvement_reports_model_invocation_id_model_invocations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_product_improvement_reports_prompt_version_id_prompt_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["review_analysis_result_id"],
            ["review_analysis_results.id"],
            name=op.f(
                "fk_product_improvement_reports_review_analysis_result_id_review_analysis_results"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_improvement_reports")),
        sa.UniqueConstraint(
            "review_analysis_result_id",
            "version",
            name="uq_product_improvement_reports_result_version",
        ),
    )
    with op.batch_alter_table("product_improvement_reports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_product_improvement_reports_product_status",
            ["source_product_id", "status"],
            unique=False,
        )

    op.create_table(
        "review_analysis_evidence",
        sa.Column("result_id", sa.Uuid(), nullable=False),
        sa.Column("source_review_id", sa.String(length=100), nullable=False),
        sa.Column("source_product_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("is_mock_data", sa.Boolean(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("evidence_type", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("sentiment", sa.String(length=32), nullable=True),
        sa.Column("issue_type", sa.String(length=100), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("translated_excerpt", sa.Text(), nullable=True),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "evidence_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_review_analysis_evidence_confidence_range"),
        ),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name=op.f("ck_review_analysis_evidence_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["review_analysis_results.id"],
            name=op.f("fk_review_analysis_evidence_result_id_review_analysis_results"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_analysis_evidence")),
        sa.UniqueConstraint(
            "result_id",
            "source_review_id",
            "evidence_type",
            "label",
            name="uq_review_analysis_evidence_identity",
        ),
    )
    with op.batch_alter_table("review_analysis_evidence", schema=None) as batch_op:
        batch_op.create_index(
            "ix_review_analysis_evidence_result_type", ["result_id", "evidence_type"], unique=False
        )
        batch_op.create_index(
            "ix_review_analysis_evidence_source_review", ["source_review_id"], unique=False
        )

    op.create_table(
        "product_improvement_suggestions",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("suggestion_key", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("severity", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("frequency_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "evidence_review_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "expected_impact",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_product_improvement_suggestions_confidence_range"),
        ),
        sa.CheckConstraint(
            "evidence_count >= 0",
            name=op.f("ck_product_improvement_suggestions_evidence_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "frequency_rate >= 0 AND frequency_rate <= 1",
            name=op.f("ck_product_improvement_suggestions_frequency_rate_range"),
        ),
        sa.CheckConstraint(
            "priority >= 1 AND priority <= 5",
            name=op.f("ck_product_improvement_suggestions_priority_range"),
        ),
        sa.CheckConstraint(
            "severity >= 0 AND severity <= 1",
            name=op.f("ck_product_improvement_suggestions_severity_range"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["product_improvement_reports.id"],
            name=op.f("fk_product_improvement_suggestions_report_id_product_improvement_reports"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_improvement_suggestions")),
        sa.UniqueConstraint(
            "report_id", "suggestion_key", name="uq_product_improvement_suggestions_report_key"
        ),
    )
    with op.batch_alter_table("product_improvement_suggestions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_product_improvement_suggestions_report_priority",
            ["report_id", "priority"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_improvement_suggestions", schema=None) as batch_op:
        batch_op.drop_index("ix_product_improvement_suggestions_report_priority")

    op.drop_table("product_improvement_suggestions")
    with op.batch_alter_table("review_analysis_evidence", schema=None) as batch_op:
        batch_op.drop_index("ix_review_analysis_evidence_source_review")
        batch_op.drop_index("ix_review_analysis_evidence_result_type")

    op.drop_table("review_analysis_evidence")
    with op.batch_alter_table("product_improvement_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_product_improvement_reports_product_status")

    op.drop_table("product_improvement_reports")
    with op.batch_alter_table("review_analysis_results", schema=None) as batch_op:
        batch_op.drop_index("ix_review_analysis_results_status_created_at")
        batch_op.drop_index("ix_review_analysis_results_product_created_at")

    op.drop_table("review_analysis_results")
    with op.batch_alter_table("product_content_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_product_content_versions_content_created_at")

    op.drop_table("product_content_versions")
    with op.batch_alter_table("generated_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_generated_reports_status_created_at")
        batch_op.drop_index("ix_generated_reports_source")

    op.drop_table("generated_reports")
    with op.batch_alter_table("product_selection_results", schema=None) as batch_op:
        batch_op.drop_index("ix_product_selection_results_task_rank")
        batch_op.drop_index("ix_product_selection_results_product_created_at")

    op.drop_table("product_selection_results")
    with op.batch_alter_table("model_invocations", schema=None) as batch_op:
        batch_op.drop_index("ix_model_invocations_status_created_at")
        batch_op.drop_index("ix_model_invocations_model_created_at")
        batch_op.drop_index("ix_model_invocations_agent_task_id")

    op.drop_table("model_invocations")
    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_prompt_versions_template_created_at")

    op.drop_table("prompt_versions")
    with op.batch_alter_table("product_selection_tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_product_selection_tasks_status_created_at")
        batch_op.drop_index("ix_product_selection_tasks_created_by_created_at")

    op.drop_table("product_selection_tasks")
    with op.batch_alter_table("product_contents", schema=None) as batch_op:
        batch_op.drop_index("ix_product_contents_product_language_status")
        batch_op.drop_index("ix_product_contents_created_by_created_at")

    op.drop_table("product_contents")
    with op.batch_alter_table("prompt_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prompt_templates_key"))

    op.drop_table("prompt_templates")
    # ### end Alembic commands ###
